feat: add verification for Podfile existence in iOS build process

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -252,6 +252,13 @@ jobs:
           mkdir -p ios/Runner
           echo $GOOGLE_SERVICE_INFO_PLIST_BASE64 | base64 --decode > ios/Runner/GoogleService-Info.plist
 
+      - name: Verify Podfile exists
+        run: |
+          if [ ! -f ios/Podfile ]; then
+            echo "Podfile not found in ios directory. Exiting."
+            exit 1
+          fi
+
       - name: Install CocoaPods
         run: pod install --project-directory=ios
 
